# Generated by Django 4.2.7 on 2023-12-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
