# Generated by Django 4.2.7 on 2023-12-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_user_bio_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
